teashop/teashop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from index.views import index

urlpatterns = [
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teashop/users/urls.py
from django.urls import path

from .views import login_registration
app_name = 'users'

urlpatterns = [path('login-registration/', login_registration, name='login_registration')]

teashop/users/models.py
from django.db import models
from uuid import uuid4
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    id = models.UUIDField(default=uuid4, primary_key=True)
    image = models.ImageField(upload_to='users_image', null=True, blank=True)
    email = models.EmailField(unique=True, blank=False, null=False)
    is_verified_email = models.BooleanField(default=False)

teashop/users/views.py
from django.contrib import auth
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.views import View
from .form import UserLoginForm, UserRegistrationForm
from django.urls import reverse_lazy, reverse


# Create your views here.


def login_registration(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('index'))

    context = {}
    if request.method == 'POST':
        action_type = request.POST.get('action')
        if action_type is None or action_type not in ['login', 'registration']:
            return HttpResponseBadRequest()
        if action_type == 'login':
            registration_form = UserRegistrationForm(initial={'action': 'registration'})
            login_form = UserLoginForm(data=request.POST)
            if login_form.is_valid():
                username = login_form.cleaned_data.get('username')
                password = login_form.cleaned_data.get('password')
                remember_me_option = login_form.cleaned_data.get('remember_me')
                user = auth.authenticate(username=username, password=password)
                if user:
                    auth.login(request, user)
                    if not remember_me_option:
                        request.session.set_expiry(0)
                    return HttpResponseRedirect(reverse('index'))
        else:
            login_form = UserLoginForm(initial={'action': 'login'})
            registration_form = UserRegistrationForm(data=request.POST)
            if registration_form.is_valid():
                registration_form.save()
                context.update({'success_message': 'Successful registration,'
                                                   ' a confirmation email has been sent'
                                                   ' to your email'})
            else:
                context.update({'register_priority': True})

            print(registration_form.errors)

    else:
        login_form = UserLoginForm(initial={'action': 'login'})
        registration_form = UserRegistrationForm(initial={'action': 'registration'})

    context.update({'login_form': login_form,
                    'registration_form': registration_form}
                   )
    return render(request, 'users/login-register.html', context=context)

teashop/users/templates/users/login-register.html
{% extends 'index/base.html' %}

{% load static %}


<!-- all css here -->
{% block custom_css %}
    <link rel="stylesheet" href={% static 'assets/css/animate.css' %}>
    <link rel="stylesheet" href={% static 'assets/css/owl.carousel.min.css' %}>
    <link rel="stylesheet" href={% static 'assets/css/slick.css' %}>
    <link rel="stylesheet" href={% static 'assets/css/chosen.min.css' %}>
{% endblock %}

{% block content %}
    <!-- Breadcrumb Area Start -->
    <div class="breadcrumb-area bg-image-3 ptb-150">
        <div class="container">
            <div class="breadcrumb-content text-center">
                <h3>LOGIN</h3>
                <ul>
                    <li><a href="index.html">Home</a></li>
                    <li class="active">Login</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Area End -->
    <div class="login-register-area ptb-100">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 col-md-12 ml-auto mr-auto">
                    <div class="login-register-wrapper">
                        <div class="login-register-tab-list nav">
                            <a {% if not register_priority %}class="active"{% endif %} data-toggle="tab" href="#lg1">
                                <h4> login </h4>
                            </a>
                            <a {% if register_priority %}class="active"{% endif %} data-toggle="tab" href="#lg2">
                                <h4> register </h4>
                            </a>
                        </div>
                        <div class="tab-content">
                            {% if login_form.non_field_errors or registration_form.errors %}
                                <div class="alert alert-danger" role="alert">
                                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                    {{ registration_form.errors }}
                                    {{ login_form.non_field_errors }}
                                </div>
                            {% endif %}

                            {% if success_message %}
                                <div class="alert alert-success" role="alert">
                                    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                                    {{ success_message }}

                                </div>
                            {% endif %}

                            <div id="lg1" class="tab-pane {% if not register_priority %}active{% endif %}">
                                <div class="login-form-container">
                                    <div class="login-register-form">
                                        <form action="{% url 'users:login_registration' %}" method="post">
                                            {% csrf_token %}
                                            {{ login_form.username }}
                                            {{ login_form.password }}
                                            {{ login_form.action }}
                                            <div class="button-box">
                                                <div class="login-toggle-btn">
                                                    {{ login_form.remember_me }}
                                                    <label>Remember me</label>
                                                    <a href="#">Forgot Password?</a>
                                                </div>
                                                <button type="submit"><span>Login</span></button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div id="lg2" class="tab-pane {% if register_priority %} active {% endif %}">
                                <div class="login-form-container">
                                    <div class="login-register-form">
                                        <form action="{% url 'users:login_registration' %}" method="post">
                                            {% csrf_token %}
                                            {{ registration_form.username }}
                                            {{ registration_form.password1 }}
                                            {{ registration_form.password2 }}
                                            {{ registration_form.email }}
                                            {{ registration_form.action }}
                                            <div class="button-box">
                                                <button type="submit"><span>Register</span></button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

<!-- all js here -->
{% block custom_js %}
    <script src={% static 'assets/js/imagesloaded.pkgd.min.js' %}></script>
    <script src={% static 'assets/js/isotope.pkgd.min.js' %}></script>
    <script src={% static 'assets/js/ajax-mail.js' %}></script>
    <script src={% static 'assets/js/owl.carousel.min.js' %}></script>
{% endblock %}