teashop/products/urls.py
from django.urls import path

from .views import ProductsListView, ProductFilteredListView

app_name = 'products'


urlpatterns = [
    path('', ProductsListView.as_view(), name='product_list'),
    path('filter/', ProductFilteredListView.as_view(), name='filtered_product_list')
]

teashop/teashop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from index.views import index

urlpatterns = [
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teashop/users/urls.py
from django.urls import path

from .views import login_registration
app_name = 'users'

urlpatterns = [path('login-registration/', login_registration, name='login_registration')]

teashop/index/templates/index/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Title</title>
    <meta name="description" content="">
    <meta name="robots" content="noindex, follow" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href={% static 'assets/img/logo/logo2.png'%}>


    <!-- all css here -->
    <link rel="stylesheet" href={% static 'assets/css/bootstrap.min.css'%}>
    <link rel="stylesheet" href={% static 'assets/css/font-awesome.min.css'%}>
    <link rel="stylesheet" href={% static 'assets/css/themify-icons.css'%}>
    <link rel="stylesheet" href={% static 'assets/css/ionicons.min.css'%}>
    <link rel="stylesheet" href={% static 'assets/css/jquery-ui.css'%}>
    <link rel="stylesheet" href={% static 'assets/css/meanmenu.min.css'%}>
    <link rel="stylesheet" href={% static 'assets/css/style.css'%}>
    <link rel="stylesheet" href={% static 'assets/css/responsive.css'%}>
    <script src={% static 'assets/js/vendor/modernizr-2.8.3.min.js' %}></script>


    <!-- custom_css start -->
    {% block custom_css %} {% endblock %}
    <!-- custom_css end -->



</head>
<body>
<!-- header start -->
<header class="header-area gray-bg clearfix">
  <div class="header-bottom">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-4 col-6">
          <div class="logo">
            <a href="{% url 'index' %}">
              <img alt="" src={% static 'assets/img/logo/logo.png' %}>
            </a>
          </div>
        </div>
        <div class="col-lg-9 col-md-8 col-6">
          <div class="header-bottom-right">
            <div class="main-menu">
              <nav>
                <ul>
                  <li class="top-hover"><a href="{% url 'index' %}">home</a>
                  </li>
                  <li><a href="about-us.html">about</a></li>
                  <li class="mega-menu-position top-hover"><a href="{% url 'products:product_list' %}">shop</a>
                    <ul class="mega-menu">
                      <li>
                        <ul>
                          <li class="mega-menu-title">Categories</li>
                          {% for category in product_categories %}
                            <li><a href="shop.html">{{ category.name }}</a></li>
                          {% endfor %}
                        </ul>
                      </li>
                      <li>
                        <ul>
                          <li class="mega-menu-title">Brands</li>
                          {% for brand in brands %}
                            <li><a href="shop.html">{{ brand.name }}</a></li>
                          {% endfor %}
                        </ul>
                      </li>
                    </ul>
                  </li>
                  <li><a href="contact.html">contact</a></li>
                  <li class="top-hover"><a href="#">My Account</a>

                    <ul class="submenu">
                      <li><a href="my-account.html">Account</a></li>
                      <li><a href="wishlist.html">wishlist</a></li>
                        <li><a href="cart-page.html">cart page</a></li>
                    </ul>
                  </li>
                </ul>
              </nav>
            </div>
            <div class="header-currency">
              <span class="digit">RUB <i class="ti-angle-down"></i></span>
              <div class="dollar-submenu">
                <ul>
                  <li><a href="#">₽ RUB</a></li>
                  <li><a href="#">$ USD</a></li>
                  <li><a href="#">€ EUR</a></li>
                  <li><a href="#">£ GBP</a></li>
                </ul>
              </div>
            </div>
            <div class="header-cart">
              <a href="#">
                <div class="cart-icon">
                  <i class="ti-shopping-cart"></i>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="mobile-menu-area">
        <div class="mobile-menu">
          <nav id="mobile-menu-active">
            <ul class="menu-overflow">
              <li><a href="#">HOME</a>
              </li>
              <li><a href="#">ABOUT</a>
              </li>
              <li><a href="shop.html"> Shop </a>
                <ul>
                  <li><a href="#">Categories</a>
                    <ul>
                        {% for category in categories %}
                      <li><a href="shop.html">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                  </li>
                <li><a href="#">Brands</a>
                    <ul>
                        {% for brand in brands %}
                      <li><a href="shop.html">{{ brand.name }}</a></li>
                        {% endfor %}
                    </ul>
                  </li>

                </ul>
              </li>
              <li><a href="contact.html"> Contact us </a></li>
                <li class="top-hover"><a href="#">My Account</a>
                    <ul class="submenu">
                      <li><a href="my-account.html">Account</a></li>
                      <li><a href="wishlist.html">wishlist</a></li>
                        <li><a href="cart-page.html">cart page</a></li>
                    </ul>
                  </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- header end -->

<!-- content start -->
{% block content %} {% endblock %}
<!-- content end -->

<!-- Footer style Start -->
<footer class="footer-area pt-75 gray-bg-3">
  <div class="footer-top gray-bg-3 pb-35">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-6 col-sm-6">
          <div class="footer-widget mb-40">
            <div class="footer-title mb-25">
              <h4>My Account</h4>
            </div>
            <div class="footer-content">
              <ul>
                <li><a href="my-account.html">My Account</a></li>
                <li><a href="about-us.html">Order History</a></li>
                <li><a href="wishlist.html">WishList</a></li>
                <li><a href="#">Newsletter</a></li>
                <li><a href="about-us.html">Order History</a></li>
                <li><a href="#">International Orders</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
          <div class="footer-widget mb-40">
            <div class="footer-title mb-25">
              <h4>Information</h4>
            </div>
            <div class="footer-content">
              <ul>
                <li><a href="about-us.html">About Us</a></li>
                <li><a href="#">Delivery Information</a></li>
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">Terms & Conditions</a></li>
                <li><a href="#">Customer Service</a></li>
                <li><a href="#">Return Policy</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
          <div class="footer-widget mb-40">
            <div class="footer-title mb-25">
              <h4>Quick Links</h4>
            </div>
            <div class="footer-content">
              <ul>
                <li><a href="#">Support Center</a></li>
                <li><a href="#">Term & Conditions</a></li>
                <li><a href="#">Shipping</a></li>
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">Help</a></li>
                <li><a href="#">FAQS</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
          <div class="footer-widget footer-widget-red footer-black-color mb-40">
            <div class="footer-title mb-25">
              <h4>Contact Us</h4>
            </div>
            <div class="footer-about">
              <p>Your current address goes to here,120 haka, angladesh</p>
              <div class="footer-contact mt-20">
                <ul>
                  <li>(+008) 254 254 254 25487</li>
                  <li>(+009) 358 587 657 6985</li>
                </ul>
              </div>
              <div class="footer-contact mt-20">
                <ul>
                  <li>yourmail@example.com</li>
                  <li>example@admin.com</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-bottom pb-25 pt-25 gray-bg-2">
<!--    <div class="container">-->
<!--      <div class="row">-->
<!--        <div class="col-md-6">-->
<!--          <div class="payment-img f-right">-->
<!--            <a href="#">-->
<!--              <img alt="" src="assets/img/icon-img/payment.png">-->
<!--            </a>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
  </div>
</footer>
<!-- Footer style End -->

<!-- all js here -->
<script src={% static '/assets/js/vendor/jquery-1.12.0.min.js' %}></script>
<script src={% static 'assets/js/popper.js'%}></script>
<script src={% static 'assets/js/bootstrap.min.js'%}></script>
<!-- custom_js start -->
{% block custom_js %} {% endblock %}
<!-- custom_js end -->
<script src={% static 'assets/js/plugins.js'%}></script>
<script src={% static '/assets/js/main.js' %}></script>


</body>
</html>